packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@stellar/stellar-sdk"
  - "blake-hash"
  - "esbuild"
  - "prisma"
  - "protobufjs"
  - "tiny-secp256k1"
  - "usb"
